# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


variables:
- group: docker

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
# - stage: CI
#   displayName: CI stage
#   jobs:
#   - job: CIJob
#     steps:
#     - bash: |
#         docker build ./acceleration-dv/. -t saba10/acceleration-dv:latest
#         docker build ./acceleration-a/. -t saba10/acceleration-a:latest
#         docker build ./acceleration-calc/. -t saba10/acceleration-calc:latest
#         docker images

#     - bash: |
#         docker login -u $(user) -p $(password)
#         docker push saba10/acceleration-dv:latest
#         docker push saba10/acceleration-a:latest
#         docker push saba10/acceleration-calc:latest

- stage: CD
  displayName: CD stage
  pool:
    name: Default
  jobs:
  - job: CDJob
    steps:
    - task: DownloadSecureFile@1
      name: sshkey
      displayName: 'Download ssh key'
      inputs:
        secureFile: 'ec2.pem'
    - bash: |
        sudo ls

