# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


variables:
- group: docker

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- bash: |
    docker login -u $(user) -p $(password)
    docker build ./acceleration-dv/. -t saba10/acceleration-dv:latest
    docker build ./acceleration-a/. -t saba10/acceleration-a:latest
    docker build ./acceleration-calc/. -t saba10/acceleration-calc:latest
    docker images
