apiVersion: v1
kind: Service
metadata:
  name: {{ include "acceleration-a.fullname" . }}
  labels:
    {{- include "acceleration-a.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3002
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "acceleration-a.selectorLabels" . | nindent 4 }}
